# Generated by Django 2.1.7 on 2019-03-07 15:07

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('have_cover', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=64)),
                ('origin_title', models.CharField(max_length=64, null=True)),
                ('other_title', models.CharField(max_length=64, null=True)),
                ('original_work_type', models.CharField(choices=[('NOVEL', 'Novel'), ('MANGA', 'Manga'), ('GAME', 'Game'), ('ORI', 'Original'), ('OTHER', 'Other')], max_length=6, null=True)),
                ('publish_type', models.CharField(choices=[('GENERAL', 'TV & WEB'), ('MOVIE', 'MOVIE'), ('OVA', 'OVA & OAD')], max_length=8)),
                ('publish_time', models.DateField(null=True)),
                ('sum_quantity', models.IntegerField(null=True)),
                ('published_quantity', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('publish_plan', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('subtitle_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('introduction', models.TextField(null=True)),
                ('keyword', models.TextField(null=True)),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('limit_level', models.CharField(choices=[('CHILD', 'CHILD'), ('ALL', 'ALL'), ('R12', 'R12'), ('R15', 'R15'), ('R17', 'R17'), ('R18', 'R18'), ('R18G', 'R18G')], max_length=6, null=True)),
                ('relations', django.contrib.postgres.fields.jsonb.JSONField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=64)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('updater', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=None, null=True)),
                ('short_comment', models.CharField(default=None, max_length=128, null=True)),
                ('article', models.TextField(default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('watched_record', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('watched_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('WATCHING', 'Watching'), ('COMPLETE', 'Complete'), ('GIVEUP', 'GiveUp')], max_length=10)),
                ('watch_many_times', models.BooleanField()),
                ('watch_original_work', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('notice_last_quantity', models.IntegerField(default=None, null=True)),
                ('title', models.CharField(max_length=64)),
                ('sum_quantity', models.IntegerField(null=True)),
                ('published_quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_mode', models.CharField(choices=[('CLOSE', 'Close'), ('ONLY_CODE', 'OnlyCode'), ('OPEN', 'Open')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SYS', 'System'), ('CHAT', 'Chat'), ('UPDATE', 'Update')], max_length=8)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('read', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('have_cover', models.BooleanField(default=False)),
                ('animation_update_notice', models.BooleanField(default=True)),
                ('night_update_mode', models.BooleanField(default=False)),
                ('enable', models.BooleanField(default=True)),
                ('create_path', models.CharField(choices=[('REGISTER', 'Register'), ('ACTIVATE', 'Activate'), ('ADMIN', 'Administrator'), ('SYS', 'System')], max_length=8)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(default=None, null=True)),
                ('last_login_ip', models.TextField(default=None, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('enable', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField(default=None, null=True)),
                ('used_time', models.DateTimeField(default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('used_user', models.CharField(default=None, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('origin_name', models.CharField(max_length=64, null=True)),
                ('is_organization', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=64)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('updater', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('introduction', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=64)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('updater', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_by_owner', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_by_sender', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='diary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='animation',
            name='original_work_authors',
            field=models.ManyToManyField(related_name='animations_by_authors', to='api.Staff'),
        ),
        migrations.AddField(
            model_name='animation',
            name='staff_companies',
            field=models.ManyToManyField(related_name='animations_by_companies', to='api.Staff'),
        ),
        migrations.AddField(
            model_name='animation',
            name='staff_supervisors',
            field=models.ManyToManyField(related_name='animations_by_supervisors', to='api.Staff'),
        ),
        migrations.AddField(
            model_name='animation',
            name='tags',
            field=models.ManyToManyField(related_name='animations', to='api.Tag'),
        ),
    ]
