# Generated by Django 2.1.7 on 2019-03-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
