# Generated by Django 2.1.7 on 2019-03-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190309_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='have_cover',
        ),
        migrations.AddField(
            model_name='animation',
            name='cover',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='animation',
            name='limit_level',
            field=models.CharField(choices=[('ALL', 'ALL'), ('R12', 'R12'), ('R15', 'R15'), ('R17', 'R17'), ('R18', 'R18'), ('R18G', 'R18G')], max_length=6, null=True),
        ),
    ]
