# Generated by Django 2.1.7 on 2019-03-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190317_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='have_cover',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
