# Generated by Django 2.1.7 on 2019-03-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190320_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='notice_last_quantity',
        ),
        migrations.AddField(
            model_name='diary',
            name='finish_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
