# Generated by Django 2.1.7 on 2019-03-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190321_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='cover',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
