# Generated by Django 2.1.7 on 2019-03-27 09:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190322_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='published_record',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='subscription_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='watched_record',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(null=True), size=None),
        ),
    ]
